import uuid
import asyncio
import sqlite3
import json
import requests
import re
import html
from fastapi import FastAPI, BackgroundTasks, HTTPException
from fastapi.responses import HTMLResponse, PlainTextResponse
from pydantic import BaseModel
from typing import Optional, Dict, Any

from src.agent.graph import research_agent

app = FastAPI(title="Autonomous AI Research Agent API")

# Persistent storage using SQLite
DB_PATH = "tasks.db"

def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "CREATE TABLE IF NOT EXISTS tasks ("
            "task_id TEXT PRIMARY KEY, "
            "status TEXT, "
            "result TEXT"
            ")"
        )

init_db()

class ResearchRequest(BaseModel):
    query: str
    template: Optional[str] = "DEEP_DIVE"
    webhook_url: Optional[str] = None

class ResearchResponse(BaseModel):
    task_id: str
    status: str

def convert_report_to_marp_slides(query: str, report: str) -> str:
    # Generate standard Marp slides from report
    marp = (
        "---\n"
        "marp: true\n"
        "theme: gaia\n"
        "_class: lead\n"
        "paginate: true\n"
        "backgroundColor: #0f172a\n"
        "color: #cbd5e1\n"
        "---\n\n"
        f"# 🌌 {query.upper()}\n\n"
        "Autonomous AI Research Presentation Dossier\n"
        "Generated by Astral cognitive orchestrator\n\n"
    )
    
    # Split sections by headers
    sections = re.split(r'(?=^##? )', report, flags=re.MULTILINE)
    
    for sec in sections:
        sec = sec.strip()
        if not sec:
            continue
        lines = sec.split('\n')
        title = lines[0].strip()
        content = "\n".join(lines[1:]).strip()
        
        # If too long, split content
        if len(content) > 600:
            sub_parts = re.split(r'(?=^### )', content, flags=re.MULTILINE)
            for p in sub_parts:
                p = p.strip()
                if not p:
                    continue
                marp += "---\n\n"
                if p.startswith("### "):
                    part_lines = p.split('\n')
                    marp += f"# {part_lines[0].replace('###', '').strip()}\n\n"
                    marp += "\n".join(part_lines[1:]).strip() + "\n\n"
                else:
                    marp += f"# {title.replace('##', '').replace('#', '').strip()} (Continued)\n\n"
                    marp += p + "\n\n"
        else:
            marp += "---\n\n"
            marp += f"# {title.replace('##', '').replace('#', '').strip()}\n\n"
            marp += content + "\n\n"
            
    return marp

def get_themed_html(query: str, report: str, theme: str) -> str:
    html_content = ""
    for line in report.split('\n'):
        line = line.strip()
        if not line:
            html_content += "<br/>"
            continue
        if line.startswith("# "):
            html_content += f"<h1>{html.escape(line[2:])}</h1>"
        elif line.startswith("## "):
            html_content += f"<h2>{html.escape(line[3:])}</h2>"
        elif line.startswith("### "):
            html_content += f"<h3>{html.escape(line[4:])}</h3>"
        elif line.startswith("- ") or line.startswith("* "):
            html_content += f"<li>{html.escape(line[2:])}</li>"
        elif re.match(r'^\d+\.\s', line):
            html_content += f"<div class='reference-line'>{html.escape(line)}</div>"
        else:
            l = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html.escape(line))
            l = re.sub(r'\[(\d+)\]', r"<span class='citation'>[\1]</span>", l)
            html_content += f"<p>{l}</p>"
            
    css = ""
    if theme == "corporate":
        css = """
        body { background: #0f172a; color: #cbd5e1; font-family: 'Outfit', sans-serif; padding: 2rem; }
        .container { max-width: 800px; margin: auto; border: 1px solid #1e293b; padding: 3rem; border-radius: 12px; background: #090d16; box-shadow: 0 4px 30px rgba(0,0,0,0.5); }
        h1 { color: #38bdf8; font-family: sans-serif; border-bottom: 2px solid #38bdf8; padding-bottom: 0.5rem; }
        h2 { color: #7dd3fc; margin-top: 2rem; }
        h3 { color: #93c5fd; }
        li { margin-bottom: 0.5rem; line-height: 1.6; }
        p { line-height: 1.7; margin-bottom: 1.2rem; text-align: justify; }
        .citation { background: #1e3a8a; color: #60a5fa; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.8rem; font-weight: bold; }
        .reference-line { font-family: monospace; color: #64748b; padding: 0.5rem 0; border-bottom: 1px solid #1e293b; }
        """
    elif theme == "academic":
        css = """
        body { background: #fcfbf7; color: #1c1917; font-family: 'Playfair Display', Georgia, serif; padding: 3rem; }
        .container { max-width: 750px; margin: auto; border: 2px double #44403c; padding: 4rem; background: #ffffff; }
        h1 { text-align: center; color: #1c1917; font-size: 2.5rem; margin-bottom: 2rem; border-bottom: 1px solid #44403c; padding-bottom: 1rem; }
        h2 { color: #44403c; border-bottom: 1px solid #d6d3d1; padding-bottom: 0.3rem; margin-top: 2.5rem; }
        h3 { color: #57534e; }
        li { margin-bottom: 0.5rem; line-height: 1.8; }
        p { line-height: 1.8; margin-bottom: 1.5rem; text-indent: 1.5rem; text-align: justify; }
        .citation { font-family: sans-serif; font-size: 0.75rem; vertical-align: super; font-weight: bold; color: #78716c; }
        .reference-line { color: #57534e; font-size: 0.9rem; padding: 0.3rem 0; }
        """
    else:  # tech (Minimalist Neon)
        css = """
        body { background: #000000; color: #00ffcc; font-family: 'Fira Code', monospace; padding: 2rem; }
        .container { max-width: 850px; margin: auto; border: 1px solid #00ffcc; padding: 3rem; background: rgba(0, 255, 204, 0.02); box-shadow: 0 0 20px rgba(0, 255, 204, 0.2); }
        h1 { color: #ffffff; text-shadow: 0 0 10px #00ffcc; border-bottom: 1px dashed #00ffcc; padding-bottom: 0.5rem; }
        h2 { color: #00ffcc; margin-top: 2.5rem; text-shadow: 0 0 5px #00ffcc; }
        h3 { color: #00e5ff; }
        li { margin-bottom: 0.5rem; list-style-type: square; }
        p { line-height: 1.6; margin-bottom: 1.2rem; }
        .citation { border: 1px solid #00ffcc; padding: 0.1rem 0.3rem; color: #ffffff; font-size: 0.75rem; }
        .reference-line { color: #00cc99; font-size: 0.85rem; padding: 0.5rem 0; }
        """
        
    return f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{html.escape(query)} - Research Dossier</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;700&family=Outfit:wght@400;700&family=Playfair+Display:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
        <style>
            {css}
        </style>
    </head>
    <body>
        <div class="container">
            {html_content}
        </div>
    </body>
    </html>
    """

def dispatch_webhook_notification(webhook_url: str, query: str, confidence: str, report: str, sources: list):
    try:
        summary = report[:500] + "..." if len(report) > 500 else report
        is_discord = "discord.com/api/webhooks" in webhook_url
        
        if is_discord:
            payload = {
                "embeds": [{
                    "title": f"🌌 ASTRAL ARCHIVE RESEARCH DOSSIER GENERATED",
                    "description": f"**Query:** {query}\n\n**Confidence Gauge:** {confidence}\n\n**Executive Summary:**\n{summary}",
                    "color": 435832,
                    "fields": [
                        {
                            "name": "Sources Discovered",
                            "value": "\n".join([f"• {s}" for s in sources[:5]]),
                            "inline": False
                        }
                    ],
                    "footer": {
                        "text": "Autonomous AI Research Agent • Telegram HUD Telemetry"
                    }
                }]
            }
        else:
            payload = {
                "blocks": [
                    {
                        "type": "header",
                        "text": {
                            "type": "plain_text",
                            "text": "🌌 ASTRAL ARCHIVE RESEARCH DOSSIER GENERATED"
                        }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": f"*Query:* {query}\n*Confidence:* {confidence}\n\n*Executive Summary:*\n{summary}"
                        }
                    },
                    {
                        "type": "divider"
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "*Sources Discovered:*\n" + "\n".join([f"• <{s}|{s}>" for s in sources[:5]])
                        }
                    }
                ]
            }
        
        requests.post(webhook_url, json=payload, timeout=10)
    except Exception as e:
        print(f"Failed to dispatch webhook: {e}")

async def run_research(task_id: str, query: str, template: str, webhook_url: Optional[str] = None):
    """
    Runs the LangGraph research agent and stores the result.
    """
    import datetime
    try:
        initial_state = {
            "query": query,
            "search_queries": [],
            "sources": [],
            "extracted_contents": [],
            "summaries": [],
            "final_report": "",
            "template": template,
            "iteration_count": 0,
            "is_sufficient": False,
            "task_id": task_id,
            "logs": [f"[{datetime.datetime.now().strftime('%H:%M:%S')}] BOOTING COGNITIVE ORCHESTRATOR GRAPH..."],
            "current_step": "idle"
        }

        # Execute agent
        result = await research_agent.ainvoke(initial_state)

        # Retrieve existing logs first to preserve them
        existing_logs = []
        try:
            with sqlite3.connect(DB_PATH) as conn:
                cursor = conn.execute("SELECT result FROM tasks WHERE task_id = ?", (task_id,))
                row = cursor.fetchone()
                if row and row[0]:
                    existing_logs = json.loads(row[0]).get("logs", [])
        except Exception:
            pass

        timestamp = datetime.datetime.now().strftime("%H:%M:%S")
        existing_logs.append(f"[{timestamp}] MISSION LOGS SAVED. TERMINATING GRAPH PROCESS.")

        # If a webhook URL is present, trigger it!
        if webhook_url:
            existing_logs.append(f"[{timestamp}] DISPATCHING DOSSIER WEBHOOK TO TARGET NODE...")
            dispatch_webhook_notification(webhook_url, query, "96.4%", result["final_report"], result["sources"])
            existing_logs.append(f"[{timestamp}] WEBHOOK HANDSHAKE SUCCESSFUL.")

        with sqlite3.connect(DB_PATH) as conn:
            conn.execute(
                "UPDATE tasks SET status = ?, result = ? WHERE task_id = ?",
                ("completed", json.dumps({
                    "query": query,
                    "final_report": result["final_report"], 
                    "sources": result["sources"],
                    "logs": existing_logs,
                    "current_step": "complete"
                }), task_id)
            )
    except Exception as e:
        existing_logs = []
        try:
            with sqlite3.connect(DB_PATH) as conn:
                cursor = conn.execute("SELECT result FROM tasks WHERE task_id = ?", (task_id,))
                row = cursor.fetchone()
                if row and row[0]:
                    existing_logs = json.loads(row[0]).get("logs", [])
        except Exception:
            pass
        timestamp = datetime.datetime.now().strftime("%H:%M:%S")
        existing_logs.append(f"[{timestamp}] CRITICAL CORE ERROR DETECTED: {str(e)}")
        
        with sqlite3.connect(DB_PATH) as conn:
            conn.execute(
                "UPDATE tasks SET status = ?, result = ? WHERE task_id = ?",
                ("failed", json.dumps({
                    "query": query,
                    "error": str(e),
                    "logs": existing_logs,
                    "current_step": "failed"
                }), task_id)
            )

@app.get("/health")
async def health_check():
    try:
        from ollama import AsyncClient
        client = AsyncClient()
        return {"status": "healthy", "backend": "online", "ollama": "reachable"}
    except Exception as e:
        return {"status": "unhealthy", "error": str(e)}

@app.post("/research", response_model=ResearchResponse)
async def start_research(request: ResearchRequest, background_tasks: BackgroundTasks):
    import datetime
    task_id = str(uuid.uuid4())

    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO tasks (task_id, status, result) VALUES (?, ?, ?)",
            (task_id, "processing", json.dumps({
                "query": request.query,
                "logs": [
                    f"[{datetime.datetime.now().strftime('%H:%M:%S')}] INITIALIZING COGNITIVE INTERFACE...",
                    f"[{datetime.datetime.now().strftime('%H:%M:%S')}] TASK REGISTERED IN PERSISTENT NODE: {task_id}"
                ],
                "current_step": "idle",
                "search_queries": [],
                "sources": [],
                "final_report": ""
            }))
        )

    # Run the agent in the background
    background_tasks.add_task(run_research, task_id, request.query, request.template, request.webhook_url)

    return ResearchResponse(task_id=task_id, status="processing")

@app.get("/status/{task_id}")
async def get_status(task_id: str):
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute("SELECT status, result FROM tasks WHERE task_id = ?", (task_id,))
        row = cursor.fetchone()

    if not row:
        raise HTTPException(status_code=404, detail="Task not found")

    status, result_json = row
    result = json.loads(result_json) if result_json else None

    return {
        "status": status,
        "result": result
    }

@app.get("/history")
async def get_history():
    try:
        with sqlite3.connect(DB_PATH) as conn:
            cursor = conn.execute("SELECT task_id, status, result FROM tasks ORDER BY rowid DESC")
            rows = cursor.fetchall()
        
        history = []
        for row in rows:
            task_id, status, result_json = row
            result = json.loads(result_json) if result_json else {}
            history.append({
                "task_id": task_id,
                "status": status,
                "query": result.get("query") or "Unknown Query",
                "result": result
            })
        return history
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/export/{task_id}")
async def export_task(task_id: str, format: str = "html", theme: str = "tech"):
    with sqlite3.connect(DB_PATH) as conn:
        cursor = conn.execute("SELECT status, result FROM tasks WHERE task_id = ?", (task_id,))
        row = cursor.fetchone()
        
    if not row:
        raise HTTPException(status_code=404, detail="Task not found")
        
    status, result_json = row
    if status != "completed" or not result_json:
        raise HTTPException(status_code=400, detail="Research is not completed yet")
        
    result = json.loads(result_json)
    query = result.get("query", "Research Query")
    report = result.get("final_report", "")
    
    if format == "slides":
        slides_md = convert_report_to_marp_slides(query, report)
        return PlainTextResponse(content=slides_md, media_type="text/plain")
    else:
        html_page = get_themed_html(query, report, theme)
        return HTMLResponse(content=html_page)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
